### ISSUE TITLE
Create UI components `floating action button`

### ISSUE THREAD

**Issue by yuki-92c** [Tascurator/tascurator-frontend#13]
## Description

- The task is to create a shared UI component for a `floating action button`.

## Criteria

- [ ] create a `floating action button` component

## Notes

<img width="94" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/b8416a7a-5cfb-468e-9528-f9347e50ac94">

## Assignment 

|Role|Assignee |
|---|---|
|`Developer`|@Akikaze1119 |
|`Reviewer`| @akiomatic |

**Comment by akiomatic** [comment]
I think this `button-circle` is the so-called `floating action button`, but should we follow the naming convention in Figma?
@yuki-92c

**Comment by yuki-92c** [comment]
> I think this `button-circle` is the so-called `floating action button`, but should we follow the naming convention in Figma? @yuki-92c

You're right. `floating action button` makes it clearer for everyone to be on the same page. I'll change the title.

**Comment by Akikaze1119** [comment]
Note: I will start as soon as the BUTTON is implemented.
https://github.com/Tascurator/tascurator-frontend/issues/12
