### ISSUE TITLE
Implement markdown editing functionality with `Tiptap`

### ISSUE THREAD

**Issue by akiomatic** [Tascurator/tascurator-frontend#140]
## Description

The current drawer for creating or updating a task's description lacks the functionality to write markdown text. To address this, we will implement that using `Tiptap`.

## Criteria

- [ ] Implement markdown functionality with appropriate validation.
- [ ] Make sure the landlord can use the following 4 syntax only: Bold, Underline, Bullet list, and Ordered list. 

## Notes
You might need to refactor the current component's structure freely.

**Comment by Akikaze1119** [comment]
I'm closing this issue because I integrate to install `Tiptap` issue
https://github.com/Tascurator/tascurator-frontend/issues/139
