### ISSUE TITLE
Create UI components `input`

### ISSUE THREAD

**Issue by yuki-92c** [Tascurator/tascurator-frontend#15]
## Description

- The task is to create a shared UI component for `input`.

## Criteria

- [ ] create a `input` component

## Notes

- https://ui.shadcn.com/docs/components/input
<img width="225" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/14f458c5-b936-4619-b05f-bf21743d5783">

## Assignment 

|Role|Assignee |
|---|---|
|`Developer`|@Akikaze1119 |
|`Reviewer`|@yuki-92c |

**Comment by Akikaze1119** [comment]
I closed this issue because `input` component has been implemented in the below issue.
https://github.com/Tascurator/tascurator-frontend/issues/27
