### ISSUE TITLE
Implement method to get data for edit page

### ISSUE THREAD

**Issue by KaiKoide** [Tascurator/tascurator-frontend#164]
## Description

Create logic to fetch data from the database and display it on the screen for the edit page.

## Criteria

- [ ] Fetch data from `Category` table based on share_house_id
- [ ] Fetch data from `Task` table based on share_house_id
- [ ] Fetch data from `TenantPlaceHolder` table based on share_house_id
- [ ] Fetch data from `Tenant` table based on share_house_id
- [ ] Fetch data from `RotationAssignment` table based on share_house_id

**Comment by akiomatic** [comment]
I'm closing this issue because it was already resolved by PR #181 .
