### ISSUE TITLE
Create UI components `select`

### ISSUE THREAD

**Issue by yuki-92c** [Tascurator/tascurator-frontend#17]
## Description

- The task is to create a shared UI component for `select`.

## Criteria

- [ ] create a `select` component

## Notes

- https://ui.shadcn.com/docs/components/select
<img width="306" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/cc3ca7a9-48c8-495f-8b60-07e752b0eb47">

## Assignment 

|Role|Assignee |
|---|---|
|`Developer`|@akiomatic |
|`Reviewer`|@yuki-92c |

**Comment by akiomatic** [comment]
I will close this issue as we no longer need to use the `select` component in actual pages.
