### ISSUE TITLE
Checkbox clickable outside of bounding box

### ISSUE THREAD

**Issue by akiomatic** [Tascurator/tascurator-frontend#311]
## Description

In the `DeleteConfirmationDrawer`, the checkbox intended for confirming the deletion is clickable even outside of its label and bounding box.

## To Reproduce

1. Navigate to the “Delete category” confirmation drawer
2. Position the cursor to the right of the "Yes, -------" label, in the empty space
3. Attempt to click to select the checkbox

## Screenshots or videos

https://github.com/user-attachments/assets/7d3848f2-23d4-45c1-b28b-3e512a1b0163

## Expected Behavior
The checkbox should only be selectable when clicking directly within its visible bounding box and on the label itself.

## Actual Behavior
The checkbox can be selected even when clicking in the empty space to the right of the label.

**Comment by yuki-92c** [comment]
Somewhat it seems not applied so i need to reopen this issue
