### ISSUE TITLE
Revise zod schemas

### ISSUE THREAD

**Issue by akiomatic** [Tascurator/tascurator-frontend#312]
## Description

The current [schemas](https://github.com/Tascurator/tascurator-frontend/blob/develop/src/constants/schema.ts) are not perfect in terms of validations. For example, some properties do not have `trim()`, which means they can contain whitespace before and after the value. This could potentially lead to bugs for values that must be exactly the same.

## Criteria

- [x] Add `trim()` to all string values to clean up any leading or trailing whitespace
- [x] Add `uuid()` to all string UUIDs

**Comment by Akikaze1119** [comment]
Note: 
Add `trim()` to passwords in each schema. 
reference: src/constants/schema.ts
